# Specify the version for docker-compose.yml
version: "3.8"

# add the serivces needed (postgres,go)
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: golang
      POSTGRES_PASSWORD: golang
    ports:
      - "5432:5432"
    volumes: 
      - ./:/var/lib/postgresql/data

  go:
    container_name: go
    build:
      context: .
    depends_on:
      - "postgres"
    volumes:
      - ./docker:/go/src/github.com/postgres-go


volumes:
  dbdata: # create the volume for persisting data.
